### ISSUE TITLE
Error encountered while uploading a model

### ISSUE THREAD

**Issue by TRoboto** [RasaHQ/rasactl#24]
**Describe the bug**
When uploading a trained model from Rasa X UI, I get "Upload failed" with the following error in the logs:
```
[2022-01-23 08:06:21 +0000] [24] [ERROR] Exception occurred while handling uri: 'http://x.x.x.x/api/projects/default/models'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 999, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 865, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "uvloop/loop.pyx", line 1469, in getaddrinfo
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sanic/app.py", line 973, in handle_request
    response = await response
  File "/usr/local/lib/python3.8/dist-packages/rasax/community/api/decorators.py", line 247, in decorated_function
    return await await_and_return_response(args, kwargs, request)
  File "/usr/local/lib/python3.8/dist-packages/rasax/community/api/decorators.py", line 177, in await_and_return_response
    response = await response
  File "/usr/local/lib/python3.8/dist-packages/rasax/community/api/decorators.py", line 84, in decorated_function
    return await f(request, user=user, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rasax/community/api/blueprints/models.py", line 69, in upload_model
    minimum_version = await model_service.minimum_compatible_version()
  File "/usr/local/lib/python3.8/dist-packages/rasax/community/services/model_service.py", line 182, in minimum_compatible_version
    info = await stack_service.version()
  File "/usr/local/lib/python3.8/dist-packages/rasax/community/services/stack_service.py", line 124, in version
    response = await session.get(
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 1011, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway.docker.internal:5005 ssl:default [Name or service not known]
```
Uploading a model with `rasactl model upload` also fails with the following error:
```
Error: rasa server is not connected to the production environment
```
**To Reproduce**
1. Install Rasa X following the docs [here](https://rasa.com/docs/rasa-x/installation-and-setup/install/rasa-ephemeral-installer/installation#quickstart).
2. Install rasa with `pip install rasa`.
3. Create new project with `rasa init` and cd to the project.
4. Upload the model from the UI or using `rasactl model upload`

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**rasactl version***
rasactl version 1.0.1

**Comment by tczekajlo** [comment]
@TRoboto what version of Rasa OSS do you use?

**Comment by TRoboto** [comment]
```
Rasa Version      :         3.0.5
Minimum Compatible Version: 3.0.0
Rasa SDK Version  :         3.0.3
Rasa X Version    :         None
Python Version    :         3.8.10
Python Path       :         /usr/bin/python3
```

**Comment by tczekajlo** [comment]
Rasa X is not compatible with Rasa OSS 3.0.x - https://rasa.com/docs/rasa-x/changelog/compatibility-matrix/

**Comment by TRoboto** [comment]
I switched to rasa 2.8.22 as shown below, started a new project and new rasa x deployment, but still get the following error:
```
Rasa Version      :         2.8.22
Minimum Compatible Version: 2.8.9
Rasa SDK Version  :         2.8.4
Rasa X Version    :         None
Python Version    :         3.8.10
Python Path       :         /usr/bin/python3
```
Error:
```py
[2022-01-23 11:22:18 +0000] [22] [ERROR] Exception occurred while handling uri: 'http://40.87.105.72/api/projects/default/models'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sanic/app.py", line 973, in handle_request
    response = await response
  File "/usr/local/lib/python3.8/dist-packages/rasax/community/api/decorators.py", line 247, in decorated_function
    return await await_and_return_response(args, kwargs, request)
  File "/usr/local/lib/python3.8/dist-packages/rasax/community/api/decorators.py", line 177, in await_and_return_response
    response = await response
  File "/usr/local/lib/python3.8/dist-packages/rasax/community/api/decorators.py", line 84, in decorated_function
    return await f(request, user=user, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rasax/community/api/blueprints/models.py", line 69, in upload_model
    minimum_version = await model_service.minimum_compatible_version()
  File "/usr/local/lib/python3.8/dist-packages/rasax/community/services/model_service.py", line 182, in minimum_compatible_version
    info = await stack_service.version()
AttributeError: 'NoneType' object has no attribute 'version'
```

**Comment by TRoboto** [comment]
I switched to rasa 2.8.22 as shown below, started a new project and new rasa x deployment, but still get the following error:
```
Rasa Version      :         2.8.22
Minimum Compatible Version: 2.8.9
Rasa SDK Version  :         2.8.4
Rasa X Version    :         None
Python Version    :         3.8.10
Python Path       :         /usr/bin/python3
```
Error:
```py
[2022-01-23 11:22:18 +0000] [22] [ERROR] Exception occurred while handling uri: 'http://x.x.x.x/api/projects/default/models'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sanic/app.py", line 973, in handle_request
    response = await response
  File "/usr/local/lib/python3.8/dist-packages/rasax/community/api/decorators.py", line 247, in decorated_function
    return await await_and_return_response(args, kwargs, request)
  File "/usr/local/lib/python3.8/dist-packages/rasax/community/api/decorators.py", line 177, in await_and_return_response
    response = await response
  File "/usr/local/lib/python3.8/dist-packages/rasax/community/api/decorators.py", line 84, in decorated_function
    return await f(request, user=user, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rasax/community/api/blueprints/models.py", line 69, in upload_model
    minimum_version = await model_service.minimum_compatible_version()
  File "/usr/local/lib/python3.8/dist-packages/rasax/community/services/model_service.py", line 182, in minimum_compatible_version
    info = await stack_service.version()
AttributeError: 'NoneType' object has no attribute 'version'
```

**Comment by TRoboto** [comment]
Additionally when trying to train a model from the UI I get "Training failed" with the following error from logs:

```py
[2022-01-23 11:29:45 +0000] [22] [ERROR] Exception occurred while handling uri: 'http://x.x.x.x/api/projects/default/models/jobs'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sanic/app.py", line 973, in handle_request
    response = await response
  File "/usr/local/lib/python3.8/dist-packages/rasax/community/api/decorators.py", line 247, in decorated_function
    return await await_and_return_response(args, kwargs, request)
  File "/usr/local/lib/python3.8/dist-packages/rasax/community/api/decorators.py", line 177, in await_and_return_response
    response = await response
  File "/usr/local/lib/python3.8/dist-packages/rasax/community/api/decorators.py", line 84, in decorated_function
    return await f(request, user=user, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rasax/community/api/blueprints/models.py", line 249, in train_model
    stack_service = stack_services[environment]
KeyError: 'worker'
```

**Comment by TRoboto** [comment]
> @TRoboto which version of pip do you use?

pip 21.3.1 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)

**Comment by tczekajlo** [comment]
@TRoboto The latest rasactl version (1.0.2) includes a few fixes related to the `connect rasa`. Please check the version out.

I've tried to reproduce your issue using the latest version and all works.

Steps:
1. Create virtual env and install rasa 2.8.22
2. 
```
$ python3 -m venv .venv && source .venv/bin/activate && pip install -U pip==21.3.1
$ pip install rasa==2.8.22
```

2. Create a new Rasa X deployment that uses a local rasa project
```
$ mkdir rasa_project
$ cd rasa_project && rasa init
$ rasactl start -p
```

3. Connect Rasa OSS to Rasa X. I can't find in your comments that you executed the `connect rasa` commend, so be sure to execute it.

```
$ rasactl connect rasa
```

Above you can find all steps to run Rasa X + Rasa OSS using rasactl.

**Comment by TRoboto** [comment]
All is working as expected now. Thank you for your effort and for the hotfixes.
